Repository MEDIARITHMICS/plugins-nodejs-sdk, pull requests merged in 2018-07, with the labels that each got.

#61 Add force reload in ad renderer
  CHANGELOG.md
  README.md
  examples/activity-analyzer/package.json
  examples/bid-optimizer/package.json
  examples/email_router/package.json
  examples/handlebars-ad-renderer/package.json
  examples/handlebars-ad-renderer/src/MyPluginImpl.ts
  examples/handlebars-ad-renderer/src/tests/index.ts
  examples/simple-ad-renderer/package.json
  package-lock.json
  package.json
  src/mediarithmics/plugins/activity-analyzer/ActivityAnalyzerBasePlugin.ts
  src/mediarithmics/plugins/ad-renderer/base/AdRendererBasePlugin.ts
  src/mediarithmics/plugins/ad-renderer/template/AdRendererTemplatePlugin.ts
  src/mediarithmics/plugins/email-renderer/base/EmailRendererBasePlugin.ts
  src/mediarithmics/plugins/email-renderer/template/EmailRendererTemplatePlugin.ts
  src/tests/ActivityAnalyzerTests.ts
  src/tests/AdRendererBaseTests.ts
  src/tests/AdRendererRecoTests.ts
  src/tests/AudienceFeedConnector.ts
  src/tests/EmailRendererTests.ts
  src/tests/EmailRouterTests.ts
  src/tests/RecommenderTests.ts
  test_sdk_and_examples.sh
Labels: v0.5

#63 Refactor some Instance Context
  CHANGELOG.md
  src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
  src/mediarithmics/plugins/recommender/RecommenderBasePlugin.ts
Labels: S, feature

#64 External Ad Serving
  CHANGELOG.md
  README.md
  examples/handlebars-ad-renderer/src/MyPluginImpl.ts
  examples/handlebars-ad-renderer/src/tests/index.ts
  examples/simple-ad-renderer/src/tests/index.ts
  src/extra/handlebars/HandlebarsEngine.ts
  src/mediarithmics/plugins/ad-renderer/base/AdRendererBasePlugin.ts
  src/mediarithmics/plugins/ad-renderer/base/AdRendererInterface.ts
  src/mediarithmics/plugins/ad-renderer/index.ts
  src/mediarithmics/plugins/ad-renderer/utils/index.ts
  src/tests/AdRendererBaseTests.ts
Labels: M, feature

#65 Prepare 0.6.0
  README.md
  examples/activity-analyzer/package.json
  examples/bid-optimizer/package.json
  examples/email_router/package.json
  examples/handlebars-ad-renderer/package.json
  examples/simple-ad-renderer/package.json
  package-lock.json
  package.json
  update_examples_package_lock.sh
Labels: S, feature
