Repository MEDIARITHMICS/plugins-nodejs-sdk, pull requests merged in 2023-10, with the labels that each got.

#172 Revert "MICS-16538 Repair Datadog metrics"
  src/helpers/StatsClient.spec.ts
  src/helpers/StatsClient.ts
Labels: bug, M

#171 MICS-17221 Access selected identifying resources from feed instance
  src/mediarithmics/api/core/audiencesegment/AudienceSegmentInterface.ts
  src/mediarithmics/api/core/plugin/PluginPropertyInterface.ts
  src/mediarithmics/api/core/plugin/ValueInterface.ts
  src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
Labels: M, squad:productus

#174 MICS-17421 AudienceFeedConnectorBasePlugin update/create properties
  CHANGELOG.md
  src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
Labels: feature, S

#175 MICS-TYPO Fix a typo in UserDeviceTechnicalIdentifierType
  CHANGELOG.md
  src/mediarithmics/api/reference/UserIdentifierInterface.ts
Labels: bug, S
