Repository MEDIARITHMICS/plugins-nodejs-sdk, pull requests merged in 2024-06, with the labels that each got.

#196 MICS-18865 Audience feed handle error instance context
  CHANGELOG.md
  src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts
  src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
Labels: feature, S

#195 MICS-18864 Add example for audience feed
  CHANGELOG.md
  examples/audience-feed/README.md
  examples/audience-feed/package.json
  examples/audience-feed/src/ExampleAudienceFeed.ts
  examples/audience-feed/src/index.ts
  examples/audience-feed/src/tests/index.ts
  examples/audience-feed/tsconfig.json
Labels: S, M

#198 MICS-19751 Add DeviceIdRegistryResource class
  CHANGELOG.md
  src/mediarithmics/api/reference/DeviceIdRegistryInterface.ts
Labels: feature, S

#197 MICS-19677 add success/error stats for each operation_type in plugin SDK
  CHANGELOG.md
  examples/audience-feed/src/ExampleAudienceFeed.ts
  examples/audience-feed/src/tests/index.ts
  src/mediarithmics/api/core/batchupdate/BatchUpdateHandler.ts
  src/mediarithmics/api/core/batchupdate/BatchUpdateInterface.ts
  src/tests/BatchedAudienceFeedConnector.ts
Labels: feature, S

#201 MICS-19771 Realm check in feeds
  CHANGELOG.md
  src/mediarithmics/api/core/webdomain/UserAgentIdentifierRealmSelectionInterface.ts
  src/mediarithmics/index.ts
  src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
  src/tests/AudienceFeedConnector.ts
Labels: feature, M

#202 Revert "MICS-18376 sdk-computedField"
  examples/computed-field/build.sh
  examples/computed-field/package.json
  examples/computed-field/run.sh
  examples/computed-field/src/MyComputedField.ts
  examples/computed-field/src/index.ts
  examples/computed-field/src/tests/MyComputedField.test.ts
  examples/computed-field/tsconfig.json
  package-lock.json
  package.json
  src/mediarithmics/index.ts
  src/mediarithmics/plugins/common/BasePlugin.ts
  src/mediarithmics/plugins/computed-field/ComputedFieldBasePlugin.ts
Labels: bug, S
