Repository MEDIARITHMICS/plugins-nodejs-sdk, pull requests merged in 2024-07, with the labels that each got.

#205 MICS-19906 Add new generic Error class
  CHANGELOG.md
  examples/audience-feed/src/ExampleAudienceFeed.ts
  src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts
  src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
Labels: feature, M

#206 MICS-20001 reintroduce sent_items_in_success and sent_items_in_error
  CHANGELOG.md
  README.md
  examples/audience-feed/src/ExampleAudienceFeed.ts
  examples/audience-feed/src/tests/index.ts
  src/mediarithmics/api/core/batchupdate/BatchUpdateHandler.ts
  src/mediarithmics/api/core/batchupdate/BatchUpdateInterface.ts
  src/tests/BatchedAudienceFeedConnector.ts
Labels: feature, S

#207 MICS-19906 Fix typo InvalidPropertyValueError -> property_value
  src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts
Labels: bug, S
