Repository MEDIARITHMICS/plugins-nodejs-sdk, pull requests merged in 2024-09, with the labels that each got.

#210 MICS-20510 Update Computed Field plugins structure
  CHANGELOG.md
  examples/computed-field/package.json
  examples/computed-field/src/MyComputedField.ts
  examples/computed-field/src/tests/MyComputedField.test.ts
  package.json
  src/mediarithmics/plugins/computed-field/ComputedFieldBasePlugin.ts
Labels: feature, M

#211 MICS-19908 feat(audience-feed): :sparkles: update realms fetching
  src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
Labels: feature, S

#212 MICS-CASE Fix dataType case
  examples/computed-field/src/tests/MyComputedField.test.ts
  src/mediarithmics/plugins/computed-field/ComputedFieldBasePlugin.ts
Labels: bug, S
